const URL = 'http://192.168.1.10'
const PORT = '8080'
const SERVER_POST = `${URL}:${PORT}`

const NOTIFICATION_TYPE = {
  CONVENTION: 'CONVENTION'
}

const MESSAGE_TYPE = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  NOTIFY: 'NOTIFY',
  MIX: 'MIX'
}

const POST_ATTACHMENT = {
  TEXT: 'TEXT',
  IMAGE: 'image/jpeg',
  VIDEO: 'video/mp4',
  NOTIFY: 'NOTIFY',
  MIX: 'MIX'
}

const MESSAGE_NOTIFY_TYPE = {
  CHANGE_AVATAR: 'CHANGE_AVATAR',
  CHANGE_AKA: 'CHANGE_AKA',
  CHANGE_CONVENTION_NAME: 'CHANGE_CONVENTION_NAME'
}

const RESPONSE_STATUS = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR'
}

const CHAT_ITEM_TYPE = {
  OWNER_MESSAGE: 'OWNER_MESSAGE',
  USER_MESSAGE: 'USER_MESSAGE'
}

const FRIEND_STATUS = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  ACCEPTING: 'ACCEPTING',
  REFUSING: 'REFUSING',
  FRIEND: 'FRIEND'
}

const MEMBER_ROLE = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
}
export {
  SERVER_POST,
  POST_ATTACHMENT,
  MESSAGE_NOTIFY_TYPE,
  NOTIFICATION_TYPE,
  MESSAGE_TYPE,
  CHAT_ITEM_TYPE,
  FRIEND_STATUS,
  RESPONSE_STATUS,
  MEMBER_ROLE
}
